name: Building app

on:
    push:
        branches: [ "test" ]

jobs:
    app-build:
        strategy:
            matrix:
                os: [ubuntu-latest]
    

        runs-on: ${{ matrix.os }}

        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
                repository: ma3rd-nepon/sfml-app
        
          - name: Deleting old files
            run: rm -rf build/
        
          - name: Setup OpenGL
            run: |
              sudo apt-get update
              sudo apt install git automake m4 libtool build-essential libvorbis-dev
              sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev udev libudev-dev
              sudo apt-get install libopenal1 libopenal-dev
              sudo apt-get install libalut0 libalut-dev
              sudo apt-get install libsfml-dev
        
          - name: Setup FLAC
            run: |
              sudo apt-get install flac libflac12 
            
            continue-on-error: true
            
          - name: Configuring Cmake
            run: bash configure_cmake.sh 

          - name: Building App
            run: bash linux_build.sh
        
          - name: Zip app with assets
            run: |
              zip -r sfml-app.zip build/bin
        
          - name: Upload App
            uses: actions/upload-artifact@v3
            with:
                name: ${{ matrix.os }} Build
                path: |
                  /*.zip
            continue-on-error: true

