name: Building app

on:
    push:
        branches: [ "test" ]

jobs:
    app-build:
        strategy:
            matrix:
                os: [ubuntu-latest]
    

        runs-on: ${{ matrix.os }}

        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
                repository: ma3rd-nepon/sfml-app
        
          - name: Deleting old files
            run: rm -rf build/
        
          - name: Setup OpenGL
            uses: openrndr/setup-opengl@v1.1
          - run: xvfb-run glxinfo
            
          - name: Configuring Cmake
            run: bash configure_cmake.sh 

          - name: Building App
            run: bash linux_build.sh
        
          - name: Zip app with assets
            run: |
              zip -r sfml-app.zip build/bin
        
          - name: Upload App
            uses: actions/upload-artifact@v3
            with:
                name: ${{ matrix.os }} Build
                path: |
                  /*.zip
            continue-on-error: true

